### ISSUE TITLE
Does not work with Plasma 5.27.10

### ISSUE THREAD

**Issue by Davidyz** [Programie/KRunner-SSH#1]
I'm running KDE Plasma 5.27.10 on Arch Linux.

I tried installing this add-on both via the instructions in the README and via the KDE Discover application but there's no ssh entries in the KRunner menu. I can confirm that this add-on has been enabled in either cases for KRunner. I'm not sure what's the cause & how to debug, but if there's anything I can do to help locating the bug please let me know and I'll try my best to help.

**Comment by Programie** [comment]
The add-on uses your `~/.ssh/known_hosts` file to get a list of hosts.

Did you disable hashing the hosts in your SSH config as stated in the readme file?

**Comment by Davidyz** [comment]
Yes. Do I have to remove `known_hosts` and reconnect to the hosts so that the hosts in `known_hosts` get refreshed?

**Comment by Programie** [comment]
I'm not sure exactly whether you have to remove the `known_hosts` file. But you have to reconnect to every host in order to add the plain hostname to the `known_hosts` file.

**Comment by Programie** [comment]
As there was no feedback for almost one week I will close this issue.

Please reopen this issue or create a new one if you still have some issues with the add-on.
